### ISSUE TITLE
Support \ottava (again)

### ISSUE THREAD

**Issue by markk** [openlilylib/edition-engraver#29]
Hi Jan-Peter,

I see that in the old "snippets" version of the edition-engraver, there is some code to support using \ottava as an edition mod (also referenced in the example.ly file).

[module.scm#L206](https://github.com/openlilylib/snippets/blob/63d2a8d817e5a642ec1221866183553a7a83503b/editorial-tools/edition-engraver/module.scm#L206)

Neither \ottava, nor #(make-music 'OttavaMusic ...) works in the current version however, and my attempts to incorporate the code referenced above have failed as I don't really understand what's going on. 

Is there any chance that \ottava could work again?

Many thanks,

Mark

**Comment by jpvoigt** [comment]
Hi Mark,

thank you for bringing this up. The public version of the EE diverged
from the one I use here and so I wasn't aware of this issue. Applying
\ottava with the EE is a basic feature that shall work and I am looking
into it.
In the meantime I refactored some code and it seems I broke something.

I hope to fix it soon!

Jan-Peter


Am 14.05.19 um 11:50 schrieb markk:

**Comment by markk** [comment]
Many thanks Jan-Peter!

**Comment by jpvoigt** [comment]
While refactoring I dropped applying context-mods. But OttavaMusic only works when it is converted to a context-mod. I pushed a quick fix that solves the issue here.

It is a change in code that SHOULD only affect OttavaMusic and nothing else. There are no side effects to expect so I pushed directly to master. If you face something odd please let me know!

**Comment by markk** [comment]
Excellent - yes, it's working here with no immediate side effects. Thanks!
